- hosts: k8s_cluster
  become: true
  tasks:
    - name: Install containerd
      dnf:
        name: containerd
        state: present

    - name: Create containerd config dir
      file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config
      shell: |
        containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Enable SystemdCgroup
      replace:
          path: /etc/containerd/config.toml
          regexp: 'SystemdCgroup = false'
          replace: 'SystemdCgroup = true'

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: true
        state: restarted

