- hosts: k8s_control
  become: true
  tasks:
    - name: Initialize Kubernetes control plane
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Setup kubeconfig for vagrant
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        mode: 0755

    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: true
        owner: vagrant

